output-format: text

strictness: veryhigh
doc-warnings: false
test-warnings: true
member-warnings: true

ignore-paths:
  - venv
  - env
  - .env
  - .venv

pep8:
  full: true
  options:
    max-line-length: 100
  disable:
    - N815
    - E501

pylint:
  options:
    max-line-length: 100
  disable:
    - logging-fstring-interpolation
    - line-too-long
    - unused-argument
    - logging-format-interpolation

dodgy:
  run: true

ignore-patterns:
  - .+/migrations/.+
  - .+/settings/.+